---
- name: Make .ssh directory
  file: path="~/.ssh" state=directory

- name: Generate SSH key
  openssh_keypair:
    path: "~/.ssh/{{item}}"
    type: rsa
    size: 4096
    state: present
    force: no
  loop: "{{ ssh_keys }}"