---

- name: Install packages
  become: yes
  apt: name={{ packages }} state=present

- name: Install pip packages
  pip: name={{ pip_packages | join (' ') }} extra_args="--user" executable=pip3
