---

- name: Install packages
  become: yes
  apt: name={{ packages }} state=present

- name: Install pip packages
  pip: name={{ item }} extra_args="--user" executable=pip3
  loop: pip_packages
