---
#- name: Install Zsh
#  apt: name=zsh state=present

- name: Whoami
  command: whoami
  register: whoami_result
  changed_when: false
  when: env_user is not defined

- name: Install Oh My Zsh
  import_role:
    name: gantsign.oh-my-zsh
  vars:
    users:
      - username: "{{ env_user|default(whoami_result.stdout) }}"

- name: Clone Oh My Zsh plugins
  git: repo={{ item.repo }} dest=/home/{{ env_user|default(whoami_result.stdout) }}/.oh-my-zsh/custom/plugins/{{ item.name }}
  loop: "{{ oh_my_zsh_plugins_clone }}"
