---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=yes
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: "piotrkochan.ansible-environment"
      vars:
        users: []
